// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '-_g9M2RfA',
    appId: '1:648582469021:web:b9ebe60f4af93d82e80b74',
    messagingSenderId: '648582469021',
    projectId: 'escapetrialapp',
    authDomain: 'escapetrialapp.firebaseapp.com',
    storageBucket: 'escapetrialapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '-NCwQXGMwAJJlt0',
    appId: '1:648582469021:android:a19a9a7c40261c5ce80b74',
    messagingSenderId: '648582469021',
    projectId: 'escapetrialapp',
    storageBucket: 'escapetrialapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:648582469021:ios:f6078365e779d90be80b74',
    messagingSenderId: '648582469021',
    projectId: 'escapetrialapp',
    storageBucket: 'escapetrialapp.appspot.com',
    iosBundleId: 'com.example.escapenow',
  );
}
